CREATE TABLE IDENTITIES
    (IDENTITY_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT IDENTITY_PK PRIMARY KEY, 
    IDENTITY_DISPLAYNAME VARCHAR(255),
    IDENTITY_EMAIL VARCHAR(255),
    IDENTITY_BIRTHDATE DATE
    );
    
CREATE TABLE AUTHENTICATION
    (AUTHENTICATION_ID INT NOT NULL GENERATED ALWAYS AS IDENTITY CONSTRAINT AUTHENTICATION_PK PRIMARY KEY,
    AUTHENTICATION_USERNAME VARCHAR(255),
    AUTHENTICATION_PASSWORD VARCHAR(255)
 );
